### ISSUE TITLE
graph 

### ISSUE THREAD

**Issue by boolship** [artiomchi/Dual-Battery-Widget#1]
Noticed the graph is able to stretch using pinch gesture, up to a point. After a certain level of graph expansion the battery levels disappear.

**Comment by artiomchi** [comment]
I've noticed it too, actually.. it seems that this is a bug in the charting library I use. It only happens when hw acceleration is on in the app.. But if I turn it off, the chart becomes really sluggish (plus the settings dialog looks worse)
I'll be monitoring the issue, and will try to find a solution as soon as I can...

**Comment by artiomchi** [comment]
To keep this updated, the developer of the chart plugin has accepted this as an issue on their tracker.
I'm trying to find the bug in their code as well, if they don't.

Here's the open issue in their tracker: http://code.google.com/p/achartengine/issues/detail?id=57

**Comment by artiomchi** [comment]
Got an update release, version 0.8.3 that fixes the issue, at the cost of disabled hardware acceleration for the chart (possible performance decrease when zooming and panning in the chart are a small cost for getting it to work)
